version: '3.8'

services:
  db:
    image: postgres:13.7
    restart: always
    environment:
       POSTGRES_PASSWORD: db_password
    ports:
      - '5432:5432'

  backend:
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3001:3001'
    environment: 
      PORT: 3001
      DB_HOST: db
      DB_PASSWORD: db_password
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_NAME: postgres