name: CI/CD workflow
on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setupnode@v3
        with: 
          node-version: '19'
      - name: Lint frontend
        run: cd frontend/ && npm run lint
      - name: Lint backend
        run: cd backend/ && npm run lint
      